<a href="https://colab.research.google.com/github/Yogeshkumar170201/Machine-Learning/blob/main/nltk_TextProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Text Processing**

**Natural Language Pre-Processing**

In [53]:
import nltk

In [54]:
nltk.download('brown')
from nltk.corpus import brown

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!


In [104]:
brown?

In [55]:
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [56]:
brown.words()

['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', ...]

In [57]:
data = brown.sents(categories=["adventure"])

In [58]:
data

[['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...]

In [59]:
len(data)

4637

In [60]:
data[0]

['Dan',
 'Morgan',
 'told',
 'himself',
 'he',
 'would',
 'forget',
 'Ann',
 'Turner',
 '.']

In [61]:
" ".join(data[0])

'Dan Morgan told himself he would forget Ann Turner .'

In [62]:
data = brown.sents(categories=["romance"])

In [63]:
len(data)

4431

In [64]:
" ".join(data[3])

'Yet if he were not there , they would have missed him , as they would have missed the sounds of bees buzzing against the screen door in early June ; ;'

In [105]:
data = brown.sents(categories=["adventure"])

In [111]:
" ".join(data[3])

"If he had married her , he'd have been asking for trouble ."

In [67]:
brown.words()

['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', ...]

In [68]:
brown.words?

In [69]:
len(brown.words())

1161192

#**Tokenization**

In [70]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [92]:
document = """ It was a good movie. The cast was amazing and I liked the story. 
I went to the movie hall to see it.
"""


sentence = "ML is OP and @Yogesh.com likes ML"

In [93]:
sents = sent_tokenize(document)
print(sents)
print(len(sents))

[' It was a good movie.', 'The cast was amazing and I liked the story.', 'I went to the movie hall to see it.']
3


In [95]:
words = word_tokenize(sentence) # Also breaks special characters
print(words)
print(len(words))

['ML', 'is', 'OP', 'and', '@', 'Yogesh.com', 'likes', 'ML']
8


#**Stop** **Word** **Removal**

In [76]:
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [77]:
sw = set(stopwords.words('english'))

In [78]:
sw

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [80]:
text = "I am not a very good cricket player".split()
print(text)

['I', 'am', 'not', 'a', 'very', 'good', 'cricket', 'player']


In [85]:
def remove_stopwords(text, stopwords):
  useful = [w for w in text if w not in stopwords]
  return useful

In [86]:
useful_words = remove_stopwords(text, sw)
print(useful_words)

['I', 'good', 'cricket', 'player']


**Tokenization using Regex**

In [97]:
from nltk.tokenize import RegexpTokenizer

In [96]:
tokenizer = RegexpTokenizer('[a-zA-Z@.]+')
useful = tokenizer.tokenize(sentence)
print(useful)

['ML', 'is', 'OP', 'and', '@Yogesh.com', 'likes', 'ML']


**Stemming**

In [99]:
from nltk.stem import SnowballStemmer, PorterStemmer, LancasterStemmer

In [100]:
ps = PorterStemmer()

In [101]:
ps.stem('running')

'run'

In [103]:
ps.stem('laughed')

'laugh'

In [ ]:
# Snowball Stemmer is multilingual means supports other languages also

In [112]:
corpus = [
          "If he had married her , he'd have been asking for trouble .",
          "Dan Morgan told himself he would forget Ann Turner .",
          "He certainly didn't want a wife who was fickle as Ann .",
          "His plans and dreams had revolved around her so much and for so long that now he felt as if he had nothing .",
          "If he had married her , he'd have been asking for trouble ."
]

**Vectorization**

In [113]:
from sklearn.feature_extraction.text import CountVectorizer

In [116]:
cv = CountVectorizer()

In [117]:
vc = cv.fit_transform(corpus)

In [118]:
vc

<5x39 sparse matrix of type '<class 'numpy.int64'>'
	with 58 stored elements in Compressed Sparse Row format>

In [124]:
vc = vc.toarray()
print(vc)

[[0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 2 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0
  0 0 1]
 [0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
  1 1 0]
 [2 0 1 1 0 0 0 0 0 1 1 0 1 0 2 0 2 1 0 1 1 1 0 0 1 1 1 1 1 2 1 0 0 0 0 0
  0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 2 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 0]]


In [126]:
print(cv.vocabulary_)

{'if': 20, 'he': 16, 'had': 14, 'married': 22, 'her': 17, 'have': 15, 'been': 5, 'asking': 4, 'for': 12, 'trouble': 32, 'dan': 7, 'morgan': 23, 'told': 31, 'himself': 18, 'would': 38, 'forget': 13, 'ann': 1, 'turner': 33, 'certainly': 6, 'didn': 8, 'want': 34, 'wife': 37, 'who': 36, 'was': 35, 'fickle': 11, 'as': 3, 'his': 19, 'plans': 27, 'and': 0, 'dreams': 9, 'revolved': 28, 'around': 2, 'so': 29, 'much': 24, 'long': 21, 'that': 30, 'now': 26, 'felt': 10, 'nothing': 25}


In [123]:
print(len(cv.vocabulary_)) # _ means generating executing fit_transform fn.

39


In [127]:
numbers = vc[2]

In [128]:
print(numbers)
print(len(numbers))

[0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 0]
39


In [129]:
len(vc[1])

39

In [131]:
def myTokenizer(document):
  words = tokenizer.tokenize(document.lower())
  #remove stopwords
  words = remove_stopwords(words, sw) #Using remove_stopwords fn.
  return words

In [132]:
myTokenizer('this is a random text')

['random', 'text']

In [136]:
cv = CountVectorizer?

In [137]:
cv = CountVectorizer(tokenizer=myTokenizer)

In [138]:
vc = cv.fit_transform(corpus).toarray()

In [139]:
print(vc)

[[1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
 [1 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1]
 [1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [1 0 1 0 0 0 1 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]]


In [140]:
len(vc)

5

In [142]:
len(vc[0])

23

In [141]:
cv.vocabulary_

{'.': 0,
 'ann': 1,
 'around': 2,
 'asking': 3,
 'certainly': 4,
 'dan': 5,
 'dreams': 6,
 'felt': 7,
 'fickle': 8,
 'forget': 9,
 'long': 10,
 'married': 11,
 'morgan': 12,
 'much': 13,
 'nothing': 14,
 'plans': 15,
 'revolved': 16,
 'told': 17,
 'trouble': 18,
 'turner': 19,
 'want': 20,
 'wife': 21,
 'would': 22}

In [147]:
cv.fit?

In [148]:
cv.transform?

In [158]:
len(cv.transform(corpus).toarray()[0])

23

In [159]:
cv.vocabulary_

{'.': 0,
 'ann': 1,
 'around': 2,
 'asking': 3,
 'certainly': 4,
 'dan': 5,
 'dreams': 6,
 'felt': 7,
 'fickle': 8,
 'forget': 9,
 'long': 10,
 'married': 11,
 'morgan': 12,
 'much': 13,
 'nothing': 14,
 'plans': 15,
 'revolved': 16,
 'told': 17,
 'trouble': 18,
 'turner': 19,
 'want': 20,
 'wife': 21,
 'would': 22}

In [ ]:
# fit_transform is used in training
#transform is used in testing